environments:
  bare_metal_pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - swarmspawner_master
      - swarmspawner_accelerator_selection
pipelines:
  swarmspawner_master:
    group: bare_metal_pypi_package
    locking: off
    materials:
      swarmspawner_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/SwarmSpawner.git
        branch: master
        destination: swarmspawner_master
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: swarmspawner_master
      TEST_DIRECTORY: swarmspawner_master
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package
  swarmspawner_accelerator_selection:
    group: bare_metal_pypi_package
    locking: off
    materials:
      swarmspawner_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/SwarmSpawner.git
        branch: accelerator_selection
        destination: swarmspawner_accelerator_selection
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: swarmspawner_accelerator_selection
      TEST_DIRECTORY: swarmspawner_accelerator_selection
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package

